# Generated by Django 5.1.4 on 2026-06-21 01:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='IndiceLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('taxa_maxima_permitida', models.DecimalField(decimal_places=4, help_text='Taxa máxima em % ao mês. Ex: 1.0000 para 1% a.m.', max_digits=8)),
                ('base_legal', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Índice Legal',
                'verbose_name_plural': 'Índices Legais',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='TipoCredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Credor',
                'verbose_name_plural': 'Tipos de Credor',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'UF',
                'verbose_name_plural': 'UFs',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Credor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cnpj_cpf', models.CharField(blank=True, max_length=18)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credores', to='core.cidade')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credores', to='core.tipocredor')),
            ],
            options={
                'verbose_name': 'Credor / Estabelecimento',
                'verbose_name_plural': 'Credores / Estabelecimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ArtigoLei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao_corpo', models.TextField()),
                ('indice_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='core.indicelegal')),
            ],
            options={
                'verbose_name': 'Artigo de Lei',
                'verbose_name_plural': 'Artigos de Lei',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas', to='core.cidade')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
                ('valor_a_vista', models.DecimalField(decimal_places=2, help_text='Valor do produto/serviço à vista', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('observacao', models.TextField(blank=True)),
                ('credor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulacoes', to='core.credor')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulacoes', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Simulação',
                'verbose_name_plural': 'Simulações',
                'ordering': ['-data_consulta'],
            },
        ),
        migrations.CreateModel(
            name='Parcelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parcelas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('periodicidade', models.IntegerField(choices=[(30, 'Mensal (30 dias)'), (15, 'Quinzenal (15 dias)'), (7, 'Semanal (7 dias)'), (1, 'Diário')], default=30, help_text='Intervalo em dias')),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelamentos', to='core.simulacao')),
            ],
            options={
                'verbose_name': 'Parcelamento',
                'verbose_name_plural': 'Parcelamentos',
            },
        ),
        migrations.CreateModel(
            name='TaxaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_taxa', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxas_extras', to='core.simulacao')),
            ],
            options={
                'verbose_name': 'Taxa Extra',
                'verbose_name_plural': 'Taxas Extras',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='core.uf'),
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('nome', 'uf')},
        ),
    ]
