# Generated by Django 5.2.14 on 2026-05-25 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndiceLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Lei de Usura', max_length=200)),
                ('taxa_maxima_permitida', models.DecimalField(decimal_places=4, help_text='Taxa em % (Ex: 1.0 para 1%)', max_digits=6)),
                ('base_legal', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cet_calculado', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='CET Calculado (Taxa Real)')),
                ('status_abusividade', models.CharField(help_text='Ex: Abusivo, Dentro da Lei', max_length=100)),
                ('parecer_juridico', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Comércio, Pessoa Física', max_length=100)),
                ('permite_cpf', models.BooleanField(default=False, verbose_name='Exige CPF?')),
                ('permite_cnpj', models.BooleanField(default=False, verbose_name='Exige CNPJ?')),
            ],
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(help_text='Ex: MG, SP', max_length=2, unique=True)),
                ('nome', models.CharField(help_text='Ex: Minas Gerais', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Credor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cnpj_cpf', models.CharField(max_length=18, unique=True, verbose_name='CNPJ ou CPF')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cidade')),
                ('tipo_credor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipocredor')),
            ],
        ),
        migrations.CreateModel(
            name='ArtigoLei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Art. 1º do Decreto 22.626/33', max_length=150)),
                ('descricao_corpo', models.TextField()),
                ('indice_legal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='app.indicelegal')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nasc', models.DateField()),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoDaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
                ('resultado_da_auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resultadoauditoria')),
            ],
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField(auto_now_add=True)),
                ('valor_a_vista', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes', to='app.credor')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes', to='app.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='resultadoauditoria',
            name='simulacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_auditoria', to='app.simulacao'),
        ),
        migrations.CreateModel(
            name='Parcelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parcelas', models.PositiveIntegerField(verbose_name='Número de Parcelas')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodicidade', models.PositiveIntegerField(help_text='Periodicidade em dias (ex: 30 para mensal)')),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelamentos', to='app.simulacao')),
            ],
        ),
        migrations.CreateModel(
            name='TaxaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_taxa', models.CharField(help_text='Ex: TAC, Seguro', max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxas_extras', to='app.simulacao')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='app.uf'),
        ),
    ]
