# Generated by Django 5.1.4 on 2026-06-21 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cet_calculado', models.DecimalField(decimal_places=4, help_text='CET em % ao mês calculado pelo sistema', max_digits=10)),
                ('cet_anual', models.DecimalField(decimal_places=4, help_text='CET em % ao ano', max_digits=10)),
                ('taxa_nominal_mensal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('acrescimo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentual_acrescimo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status_abusividade', models.CharField(choices=[('legal', 'Legal'), ('abusivo', 'Abusivo'), ('atencao', 'Atenção')], max_length=10)),
                ('parecer_juridico', models.TextField()),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('indice_referencia', models.ForeignKey(blank=True, help_text='Índice legal usado como teto para a comparação', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.indicelegal')),
                ('simulacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='core.simulacao')),
            ],
            options={
                'verbose_name': 'Resultado da Auditoria',
                'verbose_name_plural': 'Resultados das Auditorias',
                'ordering': ['-gerado_em'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to='core.cidade')),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.credor')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='auditoria.resultadoauditoria')),
            ],
            options={
                'verbose_name': 'Avaliação de Empresa',
                'verbose_name_plural': 'Avaliações de Empresas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
